import type { Config } from 'tailwindcss';

export default {
	content: [
		'./presets/**/*.{js,vue,ts}',
		'./components/**/*.{js,vue,ts}',
		'./layouts/**/*.{js,vue,ts}',
		'./pages/**/*.{js,vue,ts}',
		'./plugins/**/*.{js,ts}',
		'./models/**/*.ts',
		'./app.vue',
		'./error.vue',
	],
	theme: {
		extend: {
			colors: {
				//main
				'main-0': 'var(--main-0)',
				'main-5': 'var(--main-5)',
				'main-10': 'var(--main-10)',
				'main-15': 'var(--main-15)',
				'main-20': 'var(--main-20)',
				'main-30': 'var(--main-30)',
				'main-40': 'var(--main-40)',
				'main-50': 'var(--main-50)',
				'main-60': 'var(--main-60)',
				'main-70': 'var(--main-70)',
				'main-80': 'var(--main-80)',
				'main-85': 'var(--main-85)',
				'main-90': 'var(--main-90)',
				'main-95': 'var(--main-95)',
				'main-100': 'var(--main-100)',
				//neutral
				'neutral-0': 'var(--neutral-0)',
				'neutral-5': 'var(--neutral-5)',
				'neutral-10': 'var(--neutral-10)',
				'neutral-15': 'var(--neutral-15)',
				'neutral-20': 'var(--neutral-20)',
				'neutral-30': 'var(--neutral-30)',
				'neutral-40': 'var(--neutral-40)',
				'neutral-50': 'var(--neutral-50)',
				'neutral-60': 'var(--neutral-60)',
				'neutral-70': 'var(--neutral-70)',
				'neutral-80': 'var(--neutral-80)',
				'neutral-85': 'var(--neutral-85)',
				'neutral-90': 'var(--neutral-90)',
				'neutral-95': 'var(--neutral-95)',
				'neutral-100': 'var(--neutral-100)',
				//error
				'error-0': 'var(--error-0)',
				'error-5': 'var(--error-5)',
				'error-10': 'var(--error-10)',
				'error-15': 'var(--error-15)',
				'error-20': 'var(--error-20)',
				'error-30': 'var(--error-30)',
				'error-40': 'var(--error-40)',
				'error-50': 'var(--error-50)',
				'error-60': 'var(--error-60)',
				'error-70': 'var(--error-70)',
				'error-80': 'var(--error-80)',
				'error-85': 'var(--error-85)',
				'error-90': 'var(--error-90)',
				'error-95': 'var(--error-95)',
				'error-100': 'var(--error-100)',
				//info
				'info-0': 'var(--info-0)',
				'info-5': 'var(--info-5)',
				'info-10': 'var(--info-10)',
				'info-15': 'var(--info-15)',
				'info-20': 'var(--info-20)',
				'info-30': 'var(--info-30)',
				'info-40': 'var(--info-40)',
				'info-50': 'var(--info-50)',
				'info-60': 'var(--info-60)',
				'info-70': 'var(--info-70)',
				'info-80': 'var(--info-80)',
				'info-85': 'var(--info-85)',
				'info-90': 'var(--info-90)',
				'info-95': 'var(--info-95)',
				'info-100': 'var(--info-100)',
				//warning
				'warning-0': 'var(--warning-0)',
				'warning-5': 'var(--warning-5)',
				'warning-10': 'var(--warning-10)',
				'warning-15': 'var(--warning-15)',
				'warning-20': 'var(--warning-20)',
				'warning-30': 'var(--warning-30)',
				'warning-40': 'var(--warning-40)',
				'warning-50': 'var(--warning-50)',
				'warning-60': 'var(--warning-60)',
				'warning-70': 'var(--warning-70)',
				'warning-80': 'var(--warning-80)',
				'warning-85': 'var(--warning-85)',
				'warning-90': 'var(--warning-90)',
				'warning-95': 'var(--warning-95)',
				'warning-100': 'var(--warning-100)',
				//violet
				'violet-0': 'var(--violet-0)',
				'violet-5': 'var(--violet-5)',
				'violet-10': 'var(--violet-10)',
				'violet-15': 'var(--violet-15)',
				'violet-20': 'var(--violet-20)',
				'violet-30': 'var(--violet-30)',
				'violet-40': 'var(--violet-40)',
				'violet-50': 'var(--violet-50)',
				'violet-60': 'var(--violet-60)',
				'violet-70': 'var(--violet-70)',
				'violet-80': 'var(--violet-80)',
				'violet-85': 'var(--violet-85)',
				'violet-90': 'var(--violet-90)',
				'violet-95': 'var(--violet-95)',
				'violet-100': 'var(--violet-100)',
				//yellow
				'yellow-0': 'var(--yellow-0)',
				'yellow-5': 'var(--yellow-5)',
				'yellow-10': 'var(--yellow-10)',
				'yellow-15': 'var(--yellow-15)',
				'yellow-20': 'var(--yellow-20)',
				'yellow-30': 'var(--yellow-30)',
				'yellow-40': 'var(--yellow-40)',
				'yellow-50': 'var(--yellow-50)',
				'yellow-60': 'var(--yellow-60)',
				'yellow-70': 'var(--yellow-70)',
				'yellow-80': 'var(--yellow-80)',
				'yellow-85': 'var(--yellow-85)',
				'yellow-90': 'var(--yellow-90)',
				'yellow-95': 'var(--yellow-95)',
				'yellow-100': 'var(--yellow-100)',
				//light-green
				'light-green-0': 'var(--light-green-0)',
				'light-green-5': 'var(--light-green-5)',
				'light-green-10': 'var(--light-green-10)',
				'light-green-15': 'var(--light-green-15)',
				'light-green-20': 'var(--light-green-20)',
				'light-green-30': 'var(--light-green-30)',
				'light-green-40': 'var(--light-green-40)',
				'light-green-50': 'var(--light-green-50)',
				'light-green-60': 'var(--light-green-60)',
				'light-green-70': 'var(--light-green-70)',
				'light-green-80': 'var(--light-green-80)',
				'light-green-85': 'var(--light-green-85)',
				'light-green-90': 'var(--light-green-90)',
				'light-green-95': 'var(--light-green-95)',
				'light-green-100': 'var(--light-green-100)',
			},
			boxShadow: {
				card: '0 2px 6px 2px rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.1), -1px 1px 2px 0 rgba(0, 0, 0, 0.06);',
				tabitem: '0 1px 3px 1px rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.02);',
			},
			spacing: {
				'52.5': '210px',
			},
			fontSize: {
				'4.75': '19px',
				'4.25': '17px',
				'3.75': '15px',
				'3.25': '13px',
			},
			animation: {
				'sidebar-off': 'sidebarOff 500s ease-in-out',
				'sidebar-on': 'sidebarOn 500ms ease-in-out',
			},
			fontFamily: {
				sans: '"Inter", sans-serif',
			},
		},
	},
	plugins: [],
} satisfies Config;
